### ISSUE TITLE
LocalFileDAO 和 LocalFolderDAO 中缺少 list() 接口导致mybatis binding error

### ISSUE THREAD

**Issue by ShawyerPeng** [zhengzijie96/OneCloud#2]
您好，最近在实现一个网盘系统，您的这个项目给了我很大帮助，非常感谢~

我在运行项目的时候发现报错，导致“全部”页面显示不了文件，发现 LocalFileDAO 和 LocalFolderDAO 中缺少了 list() 接口，在这里说明一下。

然后请问一下还会继续开发其他功能吗？

**Comment by zhengzijie96** [comment]
您好，这个bug已经在最新的几个commits中修复。

为了使Hibernate实现和Mybatis实现保持一致，list()方法已经被[弃用](https://github.com/zhengzijie96/OneCloud/commit/a3d7476f3500913414ae4390ae640f56770b6fde)，在 LocalFileDAO 和 LocalFolderDAO 接口添加了[listRootContents方法](https://github.com/zhengzijie96/OneCloud/commit/538a85e52df993088bd67433ca30b0b6af91ffa5)作为替代。

暂时不打算开发其他功能，感谢您对该项目的关注与支持。
